settings:
  legacy:
    force: false
    interval: 0s
server:
  status: true
  open: true
  port: 5002
  host: localhost
schema:
- name: http
  path: .
  commands:
    run:
      status: true
  watcher:
    paths:
    - /
    extensions:
    - go
    - html
    - css
    - js
    - yaml
    ignored_paths:
    - .git
    - .realize
    - vendor
    - console
- name: console
  path: ./console
  commands:
    install:
      status: true
  watcher:
    paths:
    - /console
    extensions:
    - go